### ISSUE TITLE
Question about License and own Fork for GTNH

### ISSUE THREAD

**Issue by Dream-Master** [yorkeJohn/Tainted-Magic#81]
Hi tadashi

i have a few questions. In my modpack GT:NH for Minecraft 1.7.10 I use your Tainted magic mod.
Since most of the developers have stopped supporting Minecraft 1.7.10, I would like to ask you if i can fork your Tainted magic mod and use a custom version for my modpack.

I see you work on it from time to time beut since Feb this year i see no changes.

We just want to fix some bugs or make some minor modifications. We'll provide support on our side, and we can put the source code repository privately if you wish.
Tainted magic is very useful, and we like to continue the work on it for 1.7.10.

Here are some links if you want to know more about my modpack: 
https://www.gtnewhorizons.com/ and 
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack.
Discord: https://discord.gg/gtnh

Thanks for your attention,

DreamMasterXXL

**Comment by yorkeJohn** [comment]
Hi, thank you for your message.

If there are any game-breaking bugs, please submit a bug report ticket and I will release a patch. I am continuing to support this mod, because I know it is popular for 1.7.10 packs.

If you would like to make to the mod to better fit your modpack, I ask that you fork it to an open source repositoy and that you state that you are redistributing a modified version on the modpack website / information page.

**Comment by Dream-Master** [comment]
ok i ask my team to add code to your repo. If your version not build on my jenkins i will do a own fork copy only with a buildscript for my jenkins/nexus if this is ok.
